version: "2"
services:
  app:
    build:
      context: ./
    environment:
      - BITTREX_API_KEY=${BITTREX_API_KEY}
      - BITTREX_API_SECRET=${BITTREX_API_SECRET}
    command: yarn run watch
    volumes:
      - ./:/app